### ISSUE TITLE
Advanced search by Parliament name does not work

### ISSUE THREAD

**Issue by shavit2310** [hasadna/kikar-hamedina#268] opened 2017-05-30 10:15 UTC
Search by name=> list of optional names appear, 
but when clicking on the chosen link to upload the chosen posts , it does  not work.

So, I could not see the relent Parliament posts exclusively.

**Comment by yotammanor** [comment] 2017-07-15 15:30
Can't reproduce, closing issue.

**Closed by yotammanor** 2017-07-15 15:30 UTC
